##############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

  mariadb:
    image: mariadb:10.4
    container_name: uud-mariadb-1
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=Mmarket123!1
      - MYSQL_DATABASE=umjetnost_u_drvetu
      - MYSQL_USER=MediaMarket
      - MYSQL_PASSWORD=Mmarket123!1
    ports:
      - "3306:3306"


  webserver:
    image: nginx:alpine
    container_name: uud-webserver-1
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: uud-php-fpm-1
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
