##############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

  mariadb:
    image: mariadb:10.4
    container_name: uud-mariadb-1
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=umjetnost_u_drvetu
      - MYSQL_USER=umjetnost_u_drvetu
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"


  webserver:
    restart: always
    image: nginx:alpine
    container_name: uud-webserver-1
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx-prod.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "443:443"
      - "80:80"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: uud-php-fpm-1
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
